services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=nguyen'
      - 'POSTGRES_DB=ecom'
      - 'POSTGRES_PASSWORD=nguyen'
    volumes:
      - './volumes/nguyen/postgres:/var/lib/postgresql/data'
